version: '3'

services:
  pilates-app:
    build: .
    container_name: pilates-app
    ports:
      - "5051:5051"
    env_file:
      - .env
    volumes:
      # Lie votre dossier NAS au conteneur pour voir vos modifs en direct
      - .:/app
      # Volume anonyme pour protéger les modules (évite les conflits NAS/Conteneur)
      - /app/node_modules
    # Cette commande installe les modules manquants au démarrage puis lance le serveur
    command: sh -c "npm install --production && node server.js"
    restart: always
    extra_hosts:
      - "coolz-nas5:host-gateway"